<?php

require_once 'Mage/Checkout/controllers/CartController.php';

class PetCare_Reservation_CartController extends Mage_Checkout_CartController
{
    const RESERVATION_CATEGORY_ID = 5;
    public function _addAction ()
    {
        if($this->_initProduct()->isVirtual() && $this->isReservation($this->_initProduct())) {
            return parent::addAction();
        } else {
            return parent::addAction();
        }


    }

    public function addAction()
    {
        if (!$this->_validateFormKey()) {
            $this->_goBack();
            return;
        }
        $cart   = $this->_getCart();
        $params = $this->getRequest()->getParams();
        try {
            if (isset($params['qty'])) {
                $filter = new Zend_Filter_LocalizedToNormalized(
                    array('locale' => Mage::app()->getLocale()->getLocaleCode())
                );
                $params['qty'] = $filter->filter($params['qty']);
            }

            $product = $this->_initProduct();
            if ($product->isVirtual() && in_array(5, $product->getCategoryIds())) {
                $start = isset($params['start_date']) ? $params['start_date'] : date('Y-m-d');
                $end = isset($params['end_date']) ? $params['end_date'] : date('Y-m-d', strtotime("tomorrow"));
                // Here
                $interval = ['start_date' => $start,
                    'end_date' => $end];
                $product->addCustomOption('additional_options', serialize($interval));
                $reservation = Mage::getModel('reservation/reservation');

//                die($start);
                if (!$reservation->checkAvailableDates($start, $end)) {
                    $this->_getSession()->addError("The room cannot be reserved between $start and $end");
                }
            }


            $related = $this->getRequest()->getParam('related_product');

            /**
             * Check product availability
             */
            if (!$product) {
                $this->_goBack();
                return;
            }

            $cart->addProduct($product, $params);

//            die(var_dump($cart->getQuote()->getInterval()));
            if (!empty($related)) {
                $cart->addProductsByIds(explode(',', $related));
            }

            $cart->save();

            $this->_getSession()->setCartWasUpdated(true);

            /**
             * @todo remove wishlist observer processAddToCart
             */
            Mage::dispatchEvent('checkout_cart_add_product_complete',
                array('product' => $product, 'request' => $this->getRequest(), 'response' => $this->getResponse())
            );

            if (!$this->_getSession()->getNoCartRedirect(true)) {
                if (!$cart->getQuote()->getHasError()) {
                    $message = $this->__('%s was added to your shopping cart.', Mage::helper('core')->escapeHtml($product->getName()));
                    $this->_getSession()->addSuccess($message);
                }
                $this->_goBack();
            }
        } catch (Mage_Core_Exception $e) {
            if ($this->_getSession()->getUseNotice(true)) {
                $this->_getSession()->addNotice(Mage::helper('core')->escapeHtml($e->getMessage()));
            } else {
                $messages = array_unique(explode("\n", $e->getMessage()));
                foreach ($messages as $message) {
                    $this->_getSession()->addError(Mage::helper('core')->escapeHtml($message));
                }
            }

            $url = $this->_getSession()->getRedirectUrl(true);
            if ($url) {
                $this->getResponse()->setRedirect($url);
            } else {
                $this->_redirectReferer(Mage::helper('checkout/cart')->getCartUrl());
            }
        } catch (Exception $e) {
            $this->_getSession()->addException($e, $this->__('Cannot add the item to shopping cart.'));
            Mage::logException($e);
            $this->_goBack();
        }
    }

    public function indexAction ()
    {
//        return 1;
        parent::indexAction(); // TODO: Change the autogenerated stub
    }

    public static function isReservation($product)
    {
        $categories = $product->getCategoryIds();
        if (in_array(self::RESERVATION_CATEGORY_ID, $categories)) {
            return true;
        } else {
            return false;
        }
    }
}
